### ISSUE TITLE
Outdated starter kit

### ISSUE THREAD

**Issue by ncla** [jackabox/statamic-shopify-starter-kit#2]
Hey,

Statamic is right now at 3.3 version. The version in 3.0 version require in composer.json is out of date, and produced a PHP error when opening the site, the error was present until I upgraded to 3.3. version. Sorry I do not have the exact error at hand.

Additionally, similarly to #1, the assets in this repository are now outdated too, and the error is from outdated blueprints. You can republish assets/files with `vendor:publish`, but you have to be aware of `--force` to overwrite the files with newest changes.

**Comment by jackabox** [comment]
@ncla Hey, do you mean the plugin didn't work on 3.0, but did with 3.3?

Also, the blueprints when they need to be updated is mentioned in the update notes.

**Comment by ncla** [comment]
> Also, the blueprints when they need to be updated is mentioned in the update notes.

Where is this mentioned? I followed this page for instructions. https://statamic-shopify.jackwhiting.co.uk/starter-kit I am not updating, but evaluating your addon by installing this starter kit.

**Comment by ncla** [comment]
I dug up the error I encountered on 3.0. Here it is:

```
[2022-06-28 16:05:07] local.ERROR: Declaration of Statamic\Tags\ArrayAccessor::hasAny(array $keys) must be compatible with Illuminate\Support\Collection::hasAny($key) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Statamic\\Tags\\ArrayAccessor::hasAny(array $keys) must be compatible with Illuminate\\Support\\Collection::hasAny($key) at /var/www/html/vendor/statamic/cms/src/Tags/ArrayAccessor.php:15)
[stacktrace]
#0 {main}
"} 
```

Stack trace does not go further though for some reason. I think this happens because in the docs there are instructions to run `composer update`, which pulls in the latest statamic-shopify addon, but not latest Statamic, as it is constrained to `3.0.*` versions.

**Comment by mikemartin** [comment]
@ncla @jackabox I'm made a PR https://github.com/jackabox/statamic-shopify-starter-kit/pull/5 that updates to the latest addon JS and Statamic.
