### ISSUE TITLE
Using vendor:publish does not update JS assets due to them being under a vendor directory

### ISSUE THREAD

**Issue by ncla** [jackabox/statamic-shopify-starter-kit#4]
The site.js file references addons JS files like this.

```js
import checkout from './shopify/checkout'
import cart, { setCartCount } from './shopify/cart'
import productForm from './shopify/products'

```

This is fine, up until you do `vendor:publish` the newest version, the command publishes JS assets in `./resources/js/vendor/shopify` directory and not `./resources/js/shopify`. Please see the attached image.

![image](https://user-images.githubusercontent.com/5507083/176231105-67f4fb41-2866-4595-9b9a-06889eef01d6.png)

If you would run `yarn dev`, you would get outdated and buggy front-end, because the newest changes were not picked up.

**Comment by mikemartin** [comment]
@jackabox I came across this too when I was updating the starter kit. Should the js references be updated to /vendor/shopify to make updating easier?

**Comment by jackabox** [comment]
This has been updated now, thanks
